CREATE TABLE [dbo].[LINKS]
(
	[B_P_NOF] INT NOT NULL, 
    [B_P_CODEATIC] VARCHAR(30) NOT NULL, 
    [B_P_LIBARTIC] VARCHAR(50) NOT NULL, 
    [NOF] INT NOT NULL, 
    [CODEARTIC] VARCHAR(30) NOT NULL, 
    [LIBARTIC] VARCHAR(50) NOT NULL 
)
