CREATE TABLE [dbo].[ORDERS]
(
	[NOF] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Codeartic] VARCHAR(30) NOT NULL, 
    [LIBARTIC] VARCHAR(50) NOT NULL, 
    [VER_ART] INT NOT NULL DEFAULT 0, 
    [QTE] INT NOT NULL, 
    [DateStart] DATE NOT NULL, 
    [DateEnd] DATE NOT NULL, 
    [Priority] INT NOT NULL DEFAULT 10
)
