
CREATE TABLE [dbo].[s_group](
	[KNAPR] [char](1) NOT NULL,
	[NNAPR] [char](30) NOT NULL,
	[LEVELGR] [char](1) NOT NULL,
	[KGR] [varchar](4) NOT NULL,
	[NGR] [char](30) NOT NULL,
	[FKGR] [varchar](20) NOT NULL,
	[FNGR] [varchar](120) NOT NULL,
	[MAXLEVEL] [decimal](1, 0) NOT NULL,
	[PR_CVET] [bit] NOT NULL,
	[PR_SORT] [bit] NOT NULL,
	[PR_END] [bit] NOT NULL,
	[KPARAM] [decimal](2, 0) NOT NULL,
	[NPARAM] [char](21) NOT NULL,
	[KEI] [decimal](2, 0) NOT NULL,
	[NEI] [char](15) NOT NULL,
	[KPODTO] [char](6) NOT NULL,
	[NAMTO] [char](80) NOT NULL,
	[BRAK] [decimal](2, 0) NOT NULL,
	[DATEVRKV] [datetime] NOT NULL,
	[USERVRKV] [char](15) NULL,
	[PODRVRKV] [char](30) NULL,
	[DATEKRKV] [datetime] NULL,
	[USERKRKV] [char](15) NULL,
	[PODRKRKV] [char](30) NULL,
 ) 