--CREATE NONCLUSTERED INDEX IX_TempOperationFirst
--ON [SupportData].[TempOperations] ([Article],[KPO])
--INCLUDE ([REL],[Code],[KTOPN],[NTOP],[PONEOB],[NORMATIME],[KOB],[MOB],[KPROF],[CategoryOperation],[TitlePreactorOper],[NPP])