CREATE TABLE [InputData].[Areas]
(
	[IdArea] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Code] NVARCHAR(50) NOT NULL, 
    [Title] NVARCHAR(99) NOT NULL UNIQUE, 
    [KPO] NVARCHAR(10) NOT NULL UNIQUE, 
    [KPODTO] INT NOT NULL UNIQUE
)
GO
