CREATE FUNCTION [InputData].[tvf_GetMaterialForArticleRKVSlow]
(
	@Article NVARCHAR(99)
)
RETURNS @returntable TABLE
(
     REL		INT
	,ART		NVARCHAR(99)
	,KPODTO		INT		 
	,KTOPN		INT	
	,KPO		NVARCHAR(10)
	,NPP		INT
	,FKGR		NVARCHAR(99)
	,FNGR		NVARCHAR(99)
	,NORMA		DECIMAL(8,3)
	,KEI		INT
	,DOP		NVARCHAR(99)
	,DOPN		NVARCHAR(99)
	,TOL		NVARCHAR(99)
	,KC			NVARCHAR(10)
	,NC			NVARCHAR(99)
	,[PARAM]	NVARCHAR(10)
	,RROT		DECIMAL(6,2)
	,RRTO		DECIMAL(6,2)
)
AS
BEGIN

DECLARE @temp TABLE
(
     REL		INT
	,ART		NVARCHAR(99)
	,KPODTO		INT		 
	,KTOPN		INT	
	,KPO		NVARCHAR(10)
	,NPP		INT
	,FKGR		NVARCHAR(99)
	,FNGR		NVARCHAR(99)
	,NORMA		DECIMAL(8,3)
	,KEI		INT
	,DOP		NVARCHAR(99)
	,DOPN		NVARCHAR(99)
	,TOL		NVARCHAR(99)
	,KC			NVARCHAR(10)
	,NC			NVARCHAR(99)
	,[PARAM]	NVARCHAR(10)
	,RROT		DECIMAL(6,2)
	,RRTO		DECIMAL(6,2)
)

INSERT INTO @temp	
SELECT 
	TEMP.REL
	,P.ART
	,P.KPODTO			AS PASSPKPODTO
	,TEMP.KTOPN
	,TEMP.KPO
	,TEMP.NPP
	,P.FKGR
	,P.FNGR
	,P.NORMA
	,P.KEI
	,P.DOP
	,P.DOPN
	,P.TOL
	,P.KC
	,P.NC
	,P1.PARAM
	,P1.RROT
	,P1.RRTO
 
 FROM		[$(RKV)].[$(POTREB)].[dbo].[passp]	AS P
 LEFT JOIN	[$(RKV)].[$(POTREB)].[dbo].[passp1]	AS P1		ON	P.REL = P1.REL
 LEFT JOIN  [$(RKV)].[$(POTREB)].[dbo].[fabr1]	AS FABR1	ON  FABR1.FKGR1 = P.FKGR AND FABR1.KC = P.KC
 LEFT JOIN  [$(RKV)].[$(POTREB)].[dbo].[fabr2]	AS FABR2	ON  FABR2.REL = FABR1.REL
 LEFT JOIN 
 (
	 SELECT DISTINCT 
	 D.KPO
	,D.REL
	,F13.ART ART
	,D.NPP
	,OP.NTOP
	,KTOPN
	,M.FNGR
	,M.FKGR
	FROM		[$(RKV)].[$(PLANT)].dbo.drive	AS D 
	INNER JOIN	[$(RKV)].[$(RKV_SCAL)].dbo.F160013	AS F13	ON D.MOD=F13.MOD
	INNER JOIN	[$(RKV)].[$(PLANT)].dbo.status		AS S	ON S.MOD=D.MOD AND S.KPO=D.KPO
	INNER JOIN	[$(RKV)].[$(PLANT)].dbo.DRIVE0		AS ART	ON D.REL=ART.REL and F13.ART=ART.ART
	INNER JOIN	[$(RKV)].[$(PLANT)].dbo.drive1		AS M	ON D.REL=M.REL
	INNER JOIN	[$(RKV)].[$(PLANT)].dbo.s_top2		AS OP	ON OP.KTOP=D.KTOPN
	WHERE D.NORMA<>0  
	 
 )  AS TEMP												ON TEMP.ART = P.ART 
														AND TEMP.FKGR = P.FKGR
														AND RTRIM(TEMP.KPO) LIKE '%'+RTRIM(P.KPODTO)
 WHERE P.ART = @Article
 AND P.NORMA > 0
 AND P.PR_MAT = 1
 AND FABR2.FNGR2 IS NULL
 
UNION 
SELECT 
	TEMP.REL
	,P.ART
	,P.KPODTO			AS PASSPKPODTO
	,TEMP.KTOPN
	,TEMP.KPO
	,TEMP.NPP
	,FABR2.FKGR2
	,FABR2.FNGR2
	,FABR2.NORMA/FABR2.KOL
	,FABR2.KEI
	,P.DOP
	,P.DOPN
	,P.TOL
	,FABR2.KC
	,FABR2.NC
	,P1.PARAM
	,P1.RROT
	,P1.RRTO
 
 FROM		[$(RKV)].[$(POTREB)].[dbo].[passp]	AS P
 LEFT JOIN	[$(RKV)].[$(POTREB)].[dbo].[passp1]	AS P1		ON	P.REL = P1.REL
 LEFT JOIN  [$(RKV)].[$(POTREB)].[dbo].[fabr1]	AS FABR1	ON  FABR1.FKGR1 = P.FKGR AND FABR1.KC = P.KC
 LEFT JOIN  [$(RKV)].[$(POTREB)].[dbo].[fabr2]	AS FABR2	ON  FABR2.REL = FABR1.REL
 LEFT JOIN 
 (
	 SELECT DISTINCT 
	 D.KPO
	,D.REL
	,F13.ART ART
	,D.NPP
	,OP.NTOP
	,KTOPN
	,M.FNGR
	,M.FKGR
	FROM		[$(RKV)].[$(PLANT)].dbo.drive		AS D 
	INNER JOIN	[$(RKV)].[$(RKV_SCAL)].dbo.F160013	AS F13	ON D.MOD=F13.MOD
	INNER JOIN	[$(RKV)].[$(PLANT)].dbo.status		AS S	ON S.MOD=D.MOD AND S.KPO=D.KPO
	INNER JOIN	[$(RKV)].[$(PLANT)].dbo.DRIVE0		AS ART	ON D.REL=ART.REL and F13.ART=ART.ART
	INNER JOIN	[$(RKV)].[$(PLANT)].dbo.drive1		AS M	ON D.REL=M.REL
	INNER JOIN	[$(RKV)].[$(PLANT)].dbo.s_top2		AS OP	ON OP.KTOP=D.KTOPN
	WHERE  D.NORMA<>0  
	 
 )  AS TEMP												ON TEMP.ART = P.ART 
														AND TEMP.FKGR = P.FKGR
														AND RTRIM(TEMP.KPO) LIKE '%'+RTRIM(FABR2.KPODTO)
 WHERE P.ART = @Article
 AND P.NORMA > 0
 AND PR_MAT = 1
 AND FABR2.FNGR2 IS NOT NULL
 
 ORDER BY KPO, NPP
 INSERT INTO @returntable
 SELECT 
 CASE WHEN T.REL IS NULL THEN (SELECT TOP(1) REL FROM @temp as FN WHERE FN.KPODTO = T.KPODTO  AND FN.REL IS NOT NULL ORDER BY FN.NPP)
	  ELSE T.REL END
			,ART		 
			,KPODTO		 
			,KTOPN		 
			,KPO		 
			,NPP		 
			,FKGR		 
			,FNGR		 
			,NORMA		 
			,KEI		 
			,DOP		 
			,DOPN		 
			,TOL		 
			,KC			 
			,NC			 
			,[PARAM]	 
			,RROT		 
			,RRTO	
 FROM @temp  AS T
 RETURN
END
