CREATE VIEW [InputData].[VI_MissedAutoRoutesBetween9and92]
	AS	SELECT * FROM 
		(SELECT DISTINCT
			  vi.TitleArticle as articlefirst
			  ,AreaId as AreaFirst

		  FROM [InputData].[Rout]									AS r
		  INNER JOIN [InputData].[VI_SemiProductsWithArticles]		AS vi	ON vi.IdSemiProduct = r.SemiProductId
		  WHERE IsAutoGenerated = 1 
		  AND AreaId IN (8))										AS q1
		  LEFT JOIN 
		  (
			  SELECT DISTINCT
				  vi.TitleArticle as articlesecond
				 ,AreaId as areasecond
			  FROM [InputData].[Rout]									AS r
			  INNER JOIN [InputData].[VI_SemiProductsWithArticles]		AS vi	ON vi.IdSemiProduct = r.SemiProductId
			  WHERE IsAutoGenerated = 1 
			  AND AreaId IN (20)
		  )																AS q2 ON q1.articlefirst = q2.articlesecond
		  WHERE articlefirst is null OR articlesecond is null
