CREATE VIEW [InputData].[VI_MissingMaterialsFromNSI]
	AS 	SELECT ART
	,TITLE
	,[VALUE]
	,COLOR
	,INFO
	,NUMBER_IN_ART
	,NORMA
	,KEI
	FROM OPENQUERY(NSI, 'SELECT
      ART
	  ,CONCAT(CONCAT(EL.VALUE ||'' '',COALESCE(EL.COLOR, '' ''))||'' '', COALESCE(INFO, '' '')) title
      ,EL.VALUE
	  ,EL.COLOR
	  ,INFO
      ,EL.NUMBER_IN_ART
      ,CASE WHEN EL.CONSUMPTION_MAT_PER_PAIR IS NOT NULL THEN EL.CONSUMPTION_MAT_PER_PAIR
	        WHEN EL.COUNT_PER_PAIR IS NOT NULL THEN  EL.COUNT_PER_PAIR
	        WHEN EL.CONSUMPTION_METERS_PER_PAIR IS NOT NULL THEN  EL.CONSUMPTION_METERS_PER_PAIR
			WHEN EL.COUNT_PER_PAIR IS NOT NULL THEN  EL.COUNT_PER_PAIR
			WHEN EL.COUNT_OF_PAIRS IS NOT NULL THEN EL.COUNT_OF_PAIRS
	   ELSE NULL END AS NORMA
	  ,CASE WHEN ent.units_id = 2 THEN 36
            WHEN ent.units_id = 4 THEN 3
            WHEN ent.units_id = 3 THEN 9
            WHEN ent.units_id = 5 THEN 19
            ELSE 0 END AS KEI
	  FROM  MKZ_ART						 ART
	  INNER JOIN  MKZ_ART_ELEMENT	     EL	 ON ART.ID = EL.ID_ART
	  INNER JOIN entity					 ent ON ent.id = EL.type_item
	  WHERE EL.STATUS IS NULL')