CREATE TABLE [dbo].[s_prof2](
	[KGRPROF] [decimal](2, 0) NOT NULL,
	[NGRPROF] [char](99) NOT NULL,
	[KPROF] [decimal](5, 0) NOT NULL,
	[NPROF] [char](99) NOT NULL,
	[DATE_S] [datetime] NOT NULL,
	[USER_S] [char](30) NOT NULL,
	[PC_S] [varchar](99) NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_s_prof2] PRIMARY KEY CLUSTERED 
(
	[KPROF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
